language: node_js
node_js:
  - "4.2"
  - "5.5"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

services:
   - rabbitmq

before_install:
   - node --version | (grep  -v 'v5' && npm install -g npm@2) || true

sudo: false
